[dev]
command = "cd api && npm install && npm run start"
functions = "client/build/functions"

[build]
publish = "client/build"
command = "cd client && npm install && npm run build"

[build.environment]
NODE_ENV = "production"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200